# Archivo de ejemplo para desarrollo local.
# En Render usa variables de entorno en lugar de este archivo.

TWILIO_ACCOUNT_SID = ""
TWILIO_AUTH_TOKEN = ""
TWILIO_WHATSAPP_FROM = ""
TWILIO_CONTENT_SID_SAVE_LOCATION_CONFIRM = ""
TWILIO_CONTENT_SID_LOCATION_HELP_OFFER = ""
TWILIO_CONTENT_SID_LOCATION_HELP_STEPS = ""
TWILIO_CONTENT_SID_LOCATION_REQUIRED = ""
TWILIO_CONTENT_SID_LOCATION_SAVED_LIST = ""
TWILIO_CONTENT_SID_LOCATION_MANAGE_ACTION = ""
MAPBOX_TOKEN = ""
